# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftRealm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
  # Realm
  pod 'RealmSwift', '~> 4.0'

  # Pods for SwiftRealm

end
