# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Youtube' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Youtube
pod 'RealmSwift'
pod 'GoogleAPIClientForREST/YouTube', '~> 1.2.1'
pod 'Google/SignIn', '~> 3.0.3'
end
