# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'baitap16' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for baitap16
  pod 'RealmSwift'
end

