# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaiTapRealm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BaiTapRealm
  #Realm
  pod 'RealmSwift', '~> 4.0'
end
